# Generated by Django 4.2.3 on 2023-07-12 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30, verbose_name='모임명')),
                ('book_photo', models.ImageField(blank=True, null=True, upload_to='bookclub/', verbose_name='사진')),
                ('book_title', models.CharField(max_length=30, verbose_name='책 제목')),
                ('book_author', models.CharField(max_length=10, verbose_name='지은이')),
                ('regularity', models.BooleanField(default=False, verbose_name='정기/비정기')),
                ('date1', models.CharField(blank=True, max_length=20, verbose_name='1회 날짜')),
                ('date2', models.CharField(blank=True, max_length=20, verbose_name='2회 날짜')),
                ('date3', models.CharField(blank=True, max_length=20, verbose_name='3회 날짜')),
                ('date4', models.CharField(blank=True, max_length=20, verbose_name='4회 날짜')),
                ('date5', models.CharField(blank=True, max_length=20, verbose_name='5회 날짜')),
                ('time', models.CharField(max_length=20, verbose_name='시간')),
                ('city_location', models.CharField(max_length=10, verbose_name='장소(시/도)')),
                ('district_location', models.CharField(max_length=10, verbose_name='장소(구/시/군)')),
                ('dong_location', models.CharField(max_length=10, verbose_name='장소(동/읍/면)')),
                ('full_address', models.CharField(max_length=50, verbose_name='전체 주소')),
                ('discussion_field', models.CharField(max_length=10, verbose_name='토론 분야')),
                ('discussion_keywords', models.CharField(max_length=10, verbose_name='토론 키워드')),
                ('min_members', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='최소 멤버수')),
                ('max_members', models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='최대 멤버수')),
                ('applied_members', models.IntegerField(default=0, verbose_name='신청한 멤버수')),
                ('details', models.CharField(blank=True, max_length=400, verbose_name='클럽 상세 내용')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요 수')),
            ],
        ),
    ]
