# Generated by Django 4.2.3 on 2023-07-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='big_category',
            field=models.CharField(blank=True, max_length=10, verbose_name='카테고리1'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='middle_category',
            field=models.CharField(blank=True, max_length=10, verbose_name='카테고리2'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='small_category',
            field=models.CharField(blank=True, max_length=10, verbose_name='카테고리3'),
        ),
    ]
