# Generated by Django 4.2.3 on 2023-07-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_alter_bookclub_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='book_photo',
            field=models.ImageField(blank=True, default='bookclub/dallergut.jfif', upload_to='', verbose_name='사진'),
        ),
    ]
