# Generated by Django 4.2.3 on 2023-07-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0005_alter_bookclub_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='weakday',
            field=models.CharField(blank=True, max_length=3, verbose_name='요일'),
        ),
    ]
