# Generated by Django 4.2.3 on 2023-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0007_rename_weakday_bookclub_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='weekday',
        ),
        migrations.AddField(
            model_name='bookclub',
            name='weekday1',
            field=models.CharField(blank=True, max_length=3, verbose_name='1회 요일'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='weekday2',
            field=models.CharField(blank=True, max_length=3, verbose_name='2회 요일'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='weekday3',
            field=models.CharField(blank=True, max_length=3, verbose_name='3회 요일'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='weekday4',
            field=models.CharField(blank=True, max_length=3, verbose_name='4회 요일'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='weekday5',
            field=models.CharField(blank=True, max_length=3, verbose_name='5회 요일'),
        ),
    ]
