# Generated by Django 4.2 on 2023-07-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_title', models.TextField(verbose_name='감상문 제목')),
                ('book_photo', models.ImageField(upload_to='', verbose_name='사진 첨부')),
                ('book_title', models.TextField(verbose_name='책 제목')),
                ('book_author', models.TextField(verbose_name='책 지은이')),
                ('essay_content', models.TextField(verbose_name='상세 내용')),
                ('created_at', models.DateTimeField(verbose_name='작성일')),
                ('view_count', models.ImageField(upload_to='', verbose_name='조회수')),
            ],
        ),
    ]
