# Generated by Django 4.2 on 2023-07-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_essay_writer_alter_essay_book_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
    ]
