# Generated by Django 4.2 on 2023-07-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0004_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(max_length=400, verbose_name='내용'),
        ),
    ]
