# Generated by Django 4.2 on 2023-07-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0005_alter_comment_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='essay_likes',
            field=models.IntegerField(default=0, verbose_name='좋아요'),
        ),
    ]
